import { Book } from '../redux/booksSlice';
import { Reader } from '../redux/usersSlice';
import { Category } from '../redux/categoriesSlice';
import { Transaction } from '../redux/transactionsSlice';

export const mockCategories: Category[] = [
  { id: '1', name: 'Văn học', description: 'Sách văn học trong và ngoài nước' },
  { id: '2', name: 'Khoa học', description: 'Sách khoa học công nghệ' },
  { id: '3', name: 'Lịch sử', description: 'Sách lịch sử và tiểu sử' },
  { id: '4', name: 'Kinh tế', description: 'Sách kinh tế và quản lý' },
  { id: '5', name: 'Kỹ năng sống', description: 'Sách phát triển bản thân' },
  { id: '6', name: 'Thiếu nhi', description: 'Sách dành cho thiếu nhi' },
];

export const mockBooks: Book[] = [
  {
    id: '1',
    code: 'VH001',
    title: 'Nhà Giả Kim',
    author: 'Paulo Coelho',
    categoryId: '1',
    quantity: 10,
    available: 7,
    isHidden: false,
  },
  {
    id: '2',
    code: 'LS001',
    title: 'Sapiens: Lược Sử Loài Người',
    author: 'Yuval Noah Harari',
    categoryId: '3',
    quantity: 8,
    available: 5,
    isHidden: false,
  },
  {
    id: '3',
    code: 'VH002',
    title: 'Đắc Nhân Tâm',
    author: 'Dale Carnegie',
    categoryId: '5',
    quantity: 15,
    available: 12,
    isHidden: false,
  },
  {
    id: '4',
    code: 'KH001',
    title: 'Vũ Trụ Trong Vỏ Hạt Dẻ',
    author: 'Stephen Hawking',
    categoryId: '2',
    quantity: 5,
    available: 3,
    isHidden: false,
  },
  {
    id: '5',
    code: 'KT001',
    title: 'Từ Tốt Đến Vĩ Đại',
    author: 'Jim Collins',
    categoryId: '4',
    quantity: 7,
    available: 4,
    isHidden: false,
  },
  {
    id: '6',
    code: 'VH003',
    title: 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh',
    author: 'Nguyễn Nhật Ánh',
    categoryId: '1',
    quantity: 12,
    available: 8,
    isHidden: false,
  },
  {
    id: '7',
    code: 'KN001',
    title: 'Atomic Habits',
    author: 'James Clear',
    categoryId: '5',
    quantity: 10,
    available: 6,
    isHidden: false,
  },
  {
    id: '8',
    code: 'TN001',
    title: 'Harry Potter và Hòn Đá Phù Thủy',
    author: 'J.K. Rowling',
    categoryId: '6',
    quantity: 20,
    available: 15,
    isHidden: false,
  },
  {
    id: '9',
    code: 'LS002',
    title: 'Homo Deus: Lược Sử Tương Lai',
    author: 'Yuval Noah Harari',
    categoryId: '3',
    quantity: 6,
    available: 2,
    isHidden: false,
  },
  {
    id: '10',
    code: 'KT002',
    title: 'Nghĩ Giàu Làm Giàu',
    author: 'Napoleon Hill',
    categoryId: '4',
    quantity: 9,
    available: 7,
    isHidden: false,
  },
  {
    id: '11',
    code: 'KH002',
    title: 'Cơ Thể Người Như Thế Nào',
    author: 'Nhiều tác giả',
    categoryId: '2',
    quantity: 8,
    available: 8,
    isHidden: false,
  },
  {
    id: '12',
    code: 'VH004',
    title: 'Mắt Biếc',
    author: 'Nguyễn Nhật Ánh',
    categoryId: '1',
    quantity: 14,
    available: 10,
    isHidden: false,
  },
  {
    id: '13',
    code: 'TN002',
    title: 'Dế Mèn Phiêu Lưu Ký',
    author: 'Tô Hoài',
    categoryId: '6',
    quantity: 18,
    available: 14,
    isHidden: false,
  },
  {
    id: '14',
    code: 'KN002',
    title: 'Đời Ngắn Đừng Ngủ Dài',
    author: 'Robin Sharma',
    categoryId: '5',
    quantity: 11,
    available: 9,
    isHidden: false,
  },
  {
    id: '15',
    code: 'LS003',
    title: 'Lịch Sử Việt Nam',
    author: 'Nhiều tác giả',
    categoryId: '3',
    quantity: 10,
    available: 0,
    isHidden: false,
  },
];

export const mockReaders: Reader[] = [
  {
    id: '1',
    name: 'Nguyễn Văn A',
    email: 'nguyenvana@email.com',
    phone: '0123456789',
    borrowQuota: 5,
    currentBorrowed: 2,
    registeredDate: '2025-01-15T00:00:00.000Z',
  },
  {
    id: '2',
    name: 'Trần Thị B',
    email: 'tranthib@email.com',
    phone: '0987654321',
    borrowQuota: 5,
    currentBorrowed: 1,
    registeredDate: '2025-02-20T00:00:00.000Z',
  },
  {
    id: '3',
    name: 'Lê Văn C',
    email: 'levanc@email.com',
    phone: '0912345678',
    borrowQuota: 3,
    currentBorrowed: 0,
    registeredDate: '2025-03-10T00:00:00.000Z',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    readerId: '1',
    bookId: '1',
    borrowDate: '2025-11-15T00:00:00.000Z',
    dueDate: '2025-11-29T00:00:00.000Z',
    returnDate: null,
    status: 'borrowed',
  },
  {
    id: '2',
    readerId: '1',
    bookId: '4',
    borrowDate: '2025-11-20T00:00:00.000Z',
    dueDate: '2025-12-04T00:00:00.000Z',
    returnDate: null,
    status: 'borrowed',
  },
  {
    id: '3',
    readerId: '2',
    bookId: '7',
    borrowDate: '2025-11-18T00:00:00.000Z',
    dueDate: '2025-12-02T00:00:00.000Z',
    returnDate: null,
    status: 'borrowed',
  },
];

// Simulate delay
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
